parameters:
    app.jwtsecret: '%env(JWT_SECRET)%'
    images_directory: '%kernel.project_dir%/public/assets/uploads/images'
    upload_dir: '%kernel.project_dir%/public/uploads'
    



services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Tests/'

